### ISSUE TITLE
getting this error when running ansible-playbook prepare.yml

### ISSUE THREAD

**Issue by rabakuku** [0xBallpoint/LOAD#1]
getting this error when running ansible-playbook prepare.yml
![image](https://github.com/0xBallpoint/LOAD/assets/71357873/28d027c9-cd4f-4583-82c0-e1d5018c8c13)

The only one green is the linux server hehe

**Comment by kplei** [comment]
The URL for `ConfigureRemotingForAnsible.ps1` on line 30 of `terraform/scripts/ansibleuserdata.ps1` gets a 404. Changing to `https://raw.githubusercontent.com/ansible/ansible-documentation/devel/examples/scripts/ConfigureRemotingForAnsible.ps1` worked for me.

**Comment by hilarex** [comment]
Thanks, fixed in latest commit.
